export const BOOKS_LOADED = "BOOKS_LOADED"
export const BOOKS_ERROR = "BOOKS_ERROR"
export const USER_BOOKS_LOADED = "USER_BOOKS_LOADED"
export const USER_BOOKS_ERROR = "USER_BOOKS_ERROR"
export const WISHLIST_LOADED = "WISHLIST_LOADED"
export const WISHLIST_LOAD_ERROR = "WISHLIST_LOAD_ERROR"
export const NOTIFICATIONS_LOADED = "NOTIFICATIONS_LOADED"
export const NOTIFICATIONS_LOAD_ERROR = "NOTIFICATIONS_LOAD_ERROR"
export const COUNT_LOADED = "COUNT_LOADED"

export const BOOK_REGISTERED = "BOOK_REGISTERED"
export const REGISTER_ERROR = "REGISTER_ERROR"
export const BOOK_UPDATED = "BOOK_UPDATED"
export const UPDATE_ERROR = "UPDATE_ERROR"
export const BOOK_WISHLISTED = "BOOK_WISHLISTED"
export const BOOK_WISHLIST_ERROR = "BOOK_WISHLIST_ERROR"
export const WISHLIST_DELETED = "WISHLIST_DELETED"
export const WISHLIST_DELETE_ERROR = "WISHLIST_DELETE_ERROR"
export const NOTIFICATIONS_UPDATED = "NOTIFICATIONS_UPDATED"
export const NOTIFICATIONS_UPDATE_ERROR = "NOTIFICATIONS_UPDATE_ERROR"

export const GET_ERRORS = "GET_ERRORS"

export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const MESSAGE_SENT = "MESSAGE_SENT"
export const MESSAGE_FAIL = "MESSAGE_FAIL"
export const MESSAGE_RECEIVE = "MESSAGE_RECEIVE"
